<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>The concept of exceptions</title>
    <link rel="stylesheet" href="css/style.css" />
  </head>
  <body>
    <h1>Поняття винятків</h1>
    <h3>Типи виключень</h3>
    <p>
      <b>Виключення (помилки)</b> - це непередбачені ситуації або помилки, які
      виникають під час виконання програми. Вони можуть включати різні види
      помилок, такі як ділення на нуль, спроба доступу до неіснуючої змінної,
      відкриття неіснуючого файлу і багато інших. Коли виникає виключення,
      виконання програми призупиняється, і інтерпретатор Python намагається
      знайти відповідний обробник помилок.
    </p>
    <h3>Перехоплення винятків</h3>
    <p>
      <b>Перехоплення винятків</b> - це механізм, який дозволяє програмі
      контролювати та реагувати на виключення. У Python для цього
      використовуються такі конструкції як try, except, else та finally:
    </p>
    <ul>
      <li>
        try: Блок коду, в якому ви виконуєте код, який може викликати
        виключення. Ви маркуєте цей блок за допомогою ключового слова try.
      </li>
      <li>
        except: Блок коду, який виконується, якщо в блоку try виникає
        виключення. Ви можете вказати конкретний тип виключення, який ви хочете
        обробити, або використовувати загальний блок except, який обробляє
        будь-які виключення.
      </li>
      <li>
        else: Блок коду, який виконується, якщо в блоку try не виникло
        виключення. Це необов'язковий блок.finally: Блок коду, який завжди
        виконується, незалежно від того, чи виникали виключення, чи ні. Він
        використовується, наприклад, для виконання завершальних операцій, таких
        як закриття файлу або звільнення ресурсів.
      </li>
      <li>
        finally: Блок коду, який завжди виконується, незалежно від того, чи
        виникали виключення, чи ні. Він використовується, наприклад, для
        виконання завершальних операцій, таких як закриття файлу або звільнення
        ресурсів.
      </li>
    </ul>
    <p>Приклад обробки виключення, коли виникає помилка ділення на нуль:</p>
    <!-- exemple_1 -->
    <p>
      У цьому прикладі блок try спробує виконати ділення на нуль, але це викличе
      помилку ZeroDivisionError. Тоді програма перехоплює цю помилку у блоку
      except і виводить повідомлення про помилку. Блок else не виконується через
      виникнення виключення, а блок finally завжди виконується, незалежно від
      наявності виключень.
    </p>
    <p>
      Це дозволяє програмі обробляти помилки та забезпечувати надійність та
      стабільність в умовах, коли виникають непередбачені ситуації
    </p>
    <h3>Особливості роботи з try ... excepts</h3>
    <p>
      Щоб все працювало коректно потрібно в блок except вказувати одну із
      помилок які можуть виникати:
    </p>
    <ul>
      <li>
        SyntaxError: Виникає, коли в коді є синтаксична помилка, наприклад,
        неправильний відступ, пропущені дужки тощо.
      </li>
      <li>
        IndentationError: Виникає, коли в коді є неправильні відступи, зазвичай
        у керуючих структурах, таких як цикли та умовні оператори.
      </li>
      <li>
        NameError: Виникає, коли змінна або ім'я не визначені в поточній області
        видимості.
      </li>
      <li>
        TypeError: Виникає, коли операція або функція застосовується до об'єкта
        невідповідного типу.
      </li>
      <li>
        ValueError: Виникає, коли функція отримує аргумент правильного типу, але
        невідповідного значення.
      </li>
      <li>ZeroDivisionError: Виникає при спробі ділення на нуль.</li>
      <li>
        IndexError: Виникає, коли індекс послідовності (списку, кортежу, рядка
        тощо) знаходиться за межами діапазону.
      </li>
      <li>KeyError: Виникає, коли ключ словника не знайдено.</li>
      <li>
        FileNotFoundError: Виникає при спробі отримати доступ до неіснуючого
        файлу.
      </li>
      <li>
        IOError: Помилка вводу/виводу, що виникає при спробі читання або запису
        до файлу.
      </li>
      <li>
        AttributeError: Виникає при спробі отримати доступ до атрибуту або
        методу, який не існує в об'єкті.
      </li>
      <li>ImportError: Виникає, коли виникають проблеми з імпортом модуля.</li>
      <li>
        StopIteration: Виникає, коли функція next() викликається на ітераторі, в
        якому більше немає елементів.
      </li>
      <li>
        KeyboardInterrupt: Здіймається, коли користувач перериває виконання
        (наприклад, натискає Ctrl+C)
      </li>
      <li>
        Exception: Базовий клас для всіх винятків. Ви можете перехоплювати всі
        винятки за допомогою цього класу.
      </li>
    </ul>
  </body>
</html>
